### ISSUE TITLE
[Bug] Triceratops times out

### ISSUE THREAD

**Issue by martindevora** [stevengiacalone/triceratops#25]
Hi, I'm having trouble when using TRICERATOPS for a TESS target conaining one or more of the sectors data with 200s cadence. This is consistently happening for several targets under similar conditions. Can you take a look on that?

```
2024-04-01 14:57:00 INFO     Acquiring triceratops target
Traceback (most recent call last):
  File "/home/martin/workspace/ph/SHERLOCK/sherlockpipe/validation/validator.py", line 73, in validate
    self.execute_triceratops(cpus, self.data_dir, object_id, sectors, lc_file, transit_depth,
  File "/home/martin/workspace/ph/SHERLOCK/sherlockpipe/validation/validator.py", line 200, in execute_triceratops
    target = tr.target(ID=id_int, mission=mission, sectors=sectors)
  File "/home/martin/anaconda3/envs/sherlockpipe/lib/python3.10/site-packages/triceratops/triceratops.py", line 136, in __init__
    cutout_hdu = Tesscut.get_cutouts(
  File "/home/martin/anaconda3/envs/sherlockpipe/lib/python3.10/site-packages/astroquery/mast/cutouts.py", line 399, in get_cutouts
    response = self._service_api_connection.service_request_async("astrocut", param_dict)
  File "/home/martin/anaconda3/envs/sherlockpipe/lib/python3.10/site-packages/astroquery/utils/class_or_instance.py", line 25, in f
    return self.fn(obj, *args, **kwds)
  File "/home/martin/anaconda3/envs/sherlockpipe/lib/python3.10/site-packages/astroquery/mast/services.py", line 293, in service_request_async
    response = self._request('POST', request_url, data=catalogs_request, headers=headers, use_json=use_json)
  File "/home/martin/anaconda3/envs/sherlockpipe/lib/python3.10/site-packages/astroquery/mast/services.py", line 192, in _request
    raise TimeoutError("Timeout limit of {} exceeded.".format(self.TIMEOUT))
astroquery.exceptions.TimeoutError: Timeout limit of 600 exceeded.
```

Kind regards.

**Comment by stevengiacalone** [comment]
I'm just getting around to checking this out, but I don't seem to get an error when I initialize triceratops for that target. It looks like it's an issue with Tesscut, so maybe your environment is using a different version of astroquery? I have version 0.4.6 installed.

Let me know if the issue persists. If you have other examples of targets that fail, that would also be useful for debugging.

**Comment by stevengiacalone** [comment]
Thanks for catching that! I've approved the pull request. I'll wrap this all up in a new pip installable version some time soon.
