### ISSUE TITLE
M_s >= 0.1 assertion interrupting execution

### ISSUE THREAD

**Issue by martindevora** [stevengiacalone/triceratops#4]
Hi, I was trying to run a validation of a given target from TESS. When TRICERATOPS is analyzing the nearby stars an exception is thrown and the validation fails. The traceback is as follows:

```
Traceback (most recent call last):
  File "/home/martin/git_repositories/sherlockpipe/sherlockpipe/vet.py", line 328, in vetting
    result_dir, ra1, dec1 = self.vetting_validation(cpus, indir, tic, sectors, lc_file, transit_depth, period,
  File "/home/martin/git_repositories/sherlockpipe/sherlockpipe/vet.py", line 463, in vetting_validation
    validation_results = pool.map(validator.validate, input_n_times)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 768, in get
    raise self._value
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/home/martin/git_repositories/sherlockpipe/sherlockpipe/vet.py", line 772, in validate
    input.target.calc_probs(time=input.time, flux_0=input.flux, flux_err_0=input.sigma, P_orb=input.period)
  File "/home/martin/.local/lib/python3.8/site-packages/triceratops/triceratops.py", line 916, in calc_probs
    res, res_twin = lnZ_TEB(
  File "/home/martin/.local/lib/python3.8/site-packages/triceratops/marginal_likelihoods.py", line 174, in lnZ_TEB
    qs = sample_q(np.random.rand(N), M_s)
  File "/home/martin/.local/lib/python3.8/site-packages/triceratops/priors.py", line 172, in sample_q
    assert M_s >= 0.1
AssertionError
```

Is this done by definition for any known reason? Could TRICERATOPS just ignore the problematic star and perform a proper validation? Or we should not trust a validation that needs to ignore some of the closest nearby stars? Can a validation be done for such objects?

It also happened that we wanted to analyze a target with Ms < 0.1 and we found the same error, so this is more or less a common issue that we are finding.

Kind regards,
Martín.

**Comment by stevengiacalone** [comment]
Nearby stars need to have a mass, radius, and Teff in order to be included in .calc_probs. The latest update (1.0.8, which I just pushed) should assign Solar properties to stars without these values. This isn't a perfect solution, but it's better than ignoring them altogether, in my opinion. You can also insert your own values for mass, radius, and Teff into the .stars dataframe if you have reasonable guesses for them. 

Alternatively, you could remove nearby stars with missing properties using the new .remove_star method (see docstring in triceratops.py for usage). I only recommend doing this if that nearby star has been verified (e.g., with observations or a separate analysis) to _not_ be the source of the transit.

I've also updated the code to allow analysis of targets with M < 0.1. These modifications should prevent the code from failing on your objects, but please let me know if there are still issues.

Steven
